//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveFarmWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assortment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assortment()
        {
            this.Basket = new HashSet<Basket>();
            this.ProductsInOrder = new HashSet<ProductsInOrder>();
        }
    
        public int IdProduct { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int MakerId { get; set; }
        public int Price { get; set; }
        public int UnitId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Discount { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Makers Makers { get; set; }
        public virtual Units Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsInOrder> ProductsInOrder { get; set; }
    }
}
