//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveFarmWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ProductsInOrder = new HashSet<ProductsInOrder>();
        }
    
        public int IdOrder { get; set; }
        public int UserId { get; set; }
        public int PointId { get; set; }
        public int StatusId { get; set; }
        public string DateOrder { get; set; }
        public bool InStock { get; set; }
    
        public virtual MakingStatuses MakingStatuses { get; set; }
        public virtual PickupPoints PickupPoints { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsInOrder> ProductsInOrder { get; set; }
    }
}
